[toolchain]

[features]
seeds = false
skip-lint = false

[programs.mainnet]
escrow = "Escrow11111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet-beta"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
